CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   food_balance DECIMAL,
   meal_balance DECIMAL,
   cash_balance DECIMAL,
   CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wallets (
  balance DECIMAL,
   id_account BIGINT NOT NULL,
   category SMALLINT NOT NULL,
   CONSTRAINT pk_wallets PRIMARY KEY (id_account, category),
   CONSTRAINT FK_WALLETS_ON_ID_ACCOUNT FOREIGN KEY (id_account) REFERENCES accounts (id)
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   id_account BIGINT NOT NULL,
   total_amount DECIMAL,
   mcc VARCHAR(255),
   merchant VARCHAR(255),
   created_at TIMESTAMP NOT NULL,
   CONSTRAINT pk_transactions PRIMARY KEY (id),
   CONSTRAINT FK_TRANSACTIONS_ON_ID_ACCOUNT FOREIGN KEY (id_account) REFERENCES accounts (id)
);